-- 코드를 입력하세요
# SELECT * FROM USED_GOODS_BOARD;
# SELECT * FROM USED_GOODS_BOARD ORDER BY VIEWS desc;

SELECT CONCAT('/home/grep/src/', f.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) as FILE_PATH
FROM USED_GOODS_BOARD b
RIGHT JOIN USED_GOODS_FILE as f
    on b.BOARD_ID = f.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY f.FILE_ID DESC;

# SELECT f.*, b.VIEWS
# FROM USED_GOODS_FILE f, USED_GOODS_BOARD b
# WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD) and b.BOARD_ID = f.BOARD_ID;