-- 코드를 입력하세요
# SELECT *, date_format(CREATED_DATE, '%Y-%m-%d') CREATED_DATE FROM USED_GOODS_BOARD 
# WHERE CREATED_DATE < '2022-11-01';

SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, date_format(r.CREATED_DATE, '%Y-%m-%d') CREATED_DATE 
FROM USED_GOODS_BOARD as b
RIGHT JOIN USED_GOODS_REPLY as r
ON b.BOARD_ID = r.BOARD_ID
WHERE b.CREATED_DATE < '2022-11-01'
ORDER BY r.CREATED_DATE, b.TITLE;